version: "3.9"

services:
  pgdb:
    # Использование готового образа postgres
    image: postgres:15.2
    # Задание переменных окружения для контейнера с postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${SQL_DB_NAME}
      POSTGRES_USER: ${SQL_DB_USER}
      POSTGRES_PASSWORD: ${SQL_DB_PASSWORD}
    restart: always
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdb_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_DB_USER} -d ${SQL_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
#    build: .
    image: charfull/cw_docker:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: gunicorn todolist.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    environment:
      SQL_DB_HOST: pgdb
      SQL_DB_PORT: 5432
      SQL_DB_NAME: ${SQL_DB_NAME}
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    restart: always
    depends_on:
      pgdb:
        condition: service_healthy
    ports:
      - "800:800"
    volumes:
      - .:/app

  frontend:
    image: sermalenk/skypro-front:lesson-34
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started



volumes:
  pgdb_data:
